name: Check Mail Orders

on:
  schedule:
    - cron: '*/0 * * * *'исправить после "/" проставить минуты от 5 и более
  workflow_dispatch:

jobs:
  check-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download sent_orders.json
        uses: actions/download-artifact@v4
        with:
          name: sent-orders
          path: ./
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_MAIN: ${{ secrets.GROUP_MAIN }}
          GROUP_KEMEROVO: ${{ secrets.GROUP_KEMEROVO }}
          GROUP_KRASNOYARSK: ${{ secrets.GROUP_KRASNOYARSK }}
          GROUP_SHEREGESH: ${{ secrets.GROUP_SHEREGESH }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python src/main.py

      - name: Upload sent_orders.json
        uses: actions/upload-artifact@v4
        with:
          name: sent-orders
          path: sent_orders.json
          retention-days: 30
