name: Check Mail Orders

on:
  schedule:
    - cron: '*/2 * * * *'  # Запуск каждые 5 минут
  workflow_dispatch:      # Возможность ручного запуска

jobs:
  check-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python src/main.py
